language: go
go: 1.2

script:
 - go get github.com/stretchr/testify
 - go test -v
notifications:
  flowdock:
    secure: "gWuA+aO++JwqMD6prmIhOMjXseqYRG21N7K6fYiCH9DQ7tIBwSbKSumDpZZu4VJImwusJIJZV5FAyQ2geCxxegqNEql/dOwk8aUUQgqHOljdoP+TLKNkv6Gt46UIZcU/tpjNAYIC5GIj1/SBmsEs7FLkKjs3HOJou/tuXD4nlP4="
